#!/bin/sh

# Take a screenshot using scrot, store it on a webserver, and give the
# URL to the user using zenity.  Assumes one can ssh into the webserver
# using a key.

hosturl="http://img.bunburya.eu"
hostssh="img@bunburya.eu"
hostdir="images"

fname="$(date +%s).jpg"
tmpfile="/tmp/$fname"
if [[ "$1" = "fs" ]]; then
    scrot "$tmpfile"
else
    scrot -s "$tmpfile"
fi
notify-send "Sending screenshot to host server..."
scp -q "$tmpfile" "$hostssh:$hostdir"
scp_exit=$?
rm "$tmpfile"
case $scp_exit in
    0)
        text="$(zenity --entry\
            --text="Here is your image URL. Click OK to copy it into your X selection, or Cancel otherwise."\
            --entry-text="$hosturl/$fname")"
        if [[ -n "$text" ]]; then
            echo -n "$text" | xclip
        fi
        exit 0
        ;;
    *)
        zenity --error --text="An error occurred when sending the image to the host server."
        exit 1
esac 

